services:
  - type: web
    name: broadpeak-portal
    runtime: node
    plan: starter
    region: frankfurt
    branch: master
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: portal-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /data/data.db
      - key: GROQ_API_KEY
        value: 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
      - key: PORT
        value: "10000"
